---
title: "4장 단원문제"
author: "남승규"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 01번

---1부터 100까지의 수 중에서 3의 배수이면서 4의 배수는 아닌 수의 합을 구하라.

```{r}
sum <- 0
for (i in 1:100) {
    if (i%%3==0 & i%%4!=0) {
        sum <- sum + i
    }
}
print(sum)
```

## 02번

---x와 n을 입력하면 1부터 n까지의 수 중에서 x의 배수 합을 구해주는 사용자 정의 함수를 만들어라.

```{r}
custom <- function(x, n) {
    sum <- 0
    for (i in 1:n) {
        if (i%%x == 0) {   
            sum <- sum + i
        }
    }
    return(sum)
}
custom(3, 20)
```

## 03번

---install.packages("hflights")와 library(hflights)명령어를 이용하여 hflights 데이터를 활용할 수 있게 하자. hflights데이터에는 총 몇개의 NA가 존재하는가?

```{r}
library(hflights)
str(hflights)
sum(is.na(hflights)) # 25755
```
-New York

## 04번

---hflights 데이터에서 비행시간이 가장 긴 데이터는 몇 시간 몇 분인가?

```{r}
max_time <- max(hflights$AirTime, na.rm=T)
print(paste0(max_time%/%60,'시간 ',max_time%%60,'분'))
```
-Farenheit

## 05번

---hflights 데이터에서 비행시간이 가장 긴 데이터는 몇 시간 몇 분인가?

```{r}
max(hflights$Distance, na.rm=T)
```

##06번

---hflight 데이터에서 비행편이 취소된 건수는 몇 건인가?

```{r}
table(hflights$Cancelled)
table(hflights$Cancelled)[2]
```

