---
title: "3장 단원문제"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 01번

---x는 1분터 100까지의 수 중 3의 배수만 포함하고 y는 1부터 100까지의 수 중 4의 배수만 포함하는 벡터로 만들어라.

```{r}
x <- seq(3, 100, by=3)
x
y <- seq(4, 100, by=4)
y
```

## 02번

---01문제에서 x와 y의 교집합을 구하고, 해당 교집합에 포함된 수를 모두 더한 값을 구하라.

```{r}
sum(intersect(x, y))
```

## 03번

---airquality 데이터는 어느 도시의 공기 질을 나타낸 데이터인가?

```{r}
?airquality
```
-New York

## 04번

---airquality 데이터의 온도 단위는 무엇인가?

```{r}
?airquality
```
-Farenheit

## 05번

---airquality 데이터에서 바람이 가장 세게 분 날짜는 언제인가?

```{r}
max_wind<-max(airquality$Wind)
wind.day<-airquality[airquality$Wind==max_wind, 5:6]
wind.day
date<-paste0('1973-',wind.day$Month,'-',wind.day$Day)
date
date_type <- as.Date(date)
date_type
```

##06번

---airquality 데이터에는 총 몇개의 NA가 포함되어 있는가?

```{r}
sum(is.na(airquality))
## 혹은
table(is.na(airquality)) ## 전체 정보를 보여줌
```

##07번
---quakes 데이터는 어느 섬의 지진을 관측한 데이터인가?
```{r}
?quakes
```

--Locations of Earthquakes off Fiji : 피지섬

##08번

---quakes에 기록된 가장 큰 지진의 규모는 얼마인가?
```{r quakes}
str(quakes)
max(quakes$mag)
quakes[quakes$mag==max(quakes$mag),]
```

